INSERT INTO top_list (isbn, title, book_rating)
SELECT BOOKS.ISBN AS ISBN, BOOKS.TITLE AS Title, BOOK_RATINGS.BOOK_RATING AS Rating
FROM BOOKS, BOOK_RATINGS
WHERE BOOKS.ISBN = BOOK_RATINGS.ISBN
GROUP BY BOOK_RATINGS.BOOK_RATING
ORDER BY BOOK_RATING DESC;